### ISSUE TITLE
Linux use

### ISSUE THREAD

**Issue by Ali-ray** [madhanmaaz/cyrix86#2]
Can this work on Linux?

**Comment by madhanmaaz** [comment]
At the moment, it doesn't support Linux, but it's a possibility for future updates.

**Comment by Ali-ray** [comment]
Your cyrix86 is only connected to the computer that hosts it, it's not connected to other computer. Am I doing something wrong?

**Comment by Ali-ray** [comment]
Are you on telegram? If yes, kindly send me your username.

Thanks
